name: Pull Request Check

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

jobs:
  pr-build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop-full

    steps:
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # For better diff analysis

    - name: Setup ROS2 environment
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
        echo "ROS2 environment setup completed"

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update && apt-get install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          ros-humble-moveit \
          ros-humble-cv-bridge \
          ros-humble-vision-opencv \
          ros-humble-gazebo-ros-pkgs \
          ros-humble-tf2-geometry-msgs \
          ros-humble-image-transport \
          ros-humble-compressed-image-transport
        echo "Dependencies installed successfully"

    - name: Check changed files
      shell: bash
      run: |
        echo "## 📋 PR Analysis" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Files changed in this PR:" >> $GITHUB_STEP_SUMMARY
        git diff --name-only origin/${{ github.base_ref }}..HEAD | while read file; do
          echo "- $file" >> $GITHUB_STEP_SUMMARY
        done
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Determine affected packages
        CHANGED_PACKAGES=""
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "src/panda_moveit_control/"; then
          CHANGED_PACKAGES="$CHANGED_PACKAGES panda_moveit_control"
        fi
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "src/my_opencv_package/"; then
          CHANGED_PACKAGES="$CHANGED_PACKAGES my_opencv_package"
        fi
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "src/panda_description/"; then
          CHANGED_PACKAGES="$CHANGED_PACKAGES panda_description"
        fi
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "src/px4_ctrl/"; then
          CHANGED_PACKAGES="$CHANGED_PACKAGES px4_ctrl"
        fi
        
        echo "CHANGED_PACKAGES=$CHANGED_PACKAGES" >> $GITHUB_ENV
        echo "### Affected packages:" >> $GITHUB_STEP_SUMMARY
        if [ -n "$CHANGED_PACKAGES" ]; then
          for pkg in $CHANGED_PACKAGES; do
            echo "- $pkg" >> $GITHUB_STEP_SUMMARY
          done
        else
          echo "- No ROS packages affected" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Initialize rosdep
      shell: bash
      run: |
        rosdep init || echo "rosdep already initialized"
        rosdep update

    - name: Build affected packages
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        
        if [ -n "$CHANGED_PACKAGES" ]; then
          echo "Building changed packages: $CHANGED_PACKAGES"
          echo "Installing dependencies..."
          rosdep install --from-paths . --ignore-src -r -y --skip-keys="px4_msgs" || true
          
          # Build dependencies first
          colcon build --packages-up-to $CHANGED_PACKAGES \
            --cmake-args -DCMAKE_BUILD_TYPE=Release \
            --event-handlers console_direct+ \
            --continue-on-error
        else
          echo "No ROS packages changed, performing full build..."
          rosdep install --from-paths . --ignore-src -r -y --skip-keys="px4_msgs" || true
          colcon build --packages-ignore px4_ctrl \
            --cmake-args -DCMAKE_BUILD_TYPE=Release \
            --event-handlers console_direct+
        fi

    - name: Run quick tests
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        
        if [ -d "install" ]; then
          source install/setup.bash
          echo "✅ Workspace sourced successfully"
          
          # Quick package verification
          if [ -n "$CHANGED_PACKAGES" ]; then
            for pkg in $CHANGED_PACKAGES; do
              if ros2 pkg list | grep -q "$pkg"; then
                echo "✅ $pkg: Built successfully"
              else
                echo "❌ $pkg: Build failed"
              fi
            done
          fi
        else
          echo "❌ No install directory found"
          exit 1
        fi

    - name: Comment PR status
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const conclusion = '${{ job.status }}';
          const changedPackages = process.env.CHANGED_PACKAGES || 'None';
          
          const body = conclusion === 'success' 
            ? `✅ **PR Check Passed!**
            
            **Changed packages:** ${changedPackages}
            **Status:** All builds completed successfully
            **Action:** Ready for review`
            : `❌ **PR Check Failed!**
            
            **Changed packages:** ${changedPackages}
            **Status:** Build or test failures detected
            **Action:** Please check the logs and fix issues`;
          
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body
          });