name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  release-build:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop-full

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup ROS2 environment
      run: |
        source /opt/ros/humble/setup.bash
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          ros-humble-moveit \
          ros-humble-cv-bridge \
          ros-humble-vision-opencv \
          ros-humble-gazebo-ros-pkgs \
          ros-humble-tf2-geometry-msgs

    - name: Build optimized release
      run: |
        source /opt/ros/humble/setup.bash
        rosdep install --from-paths . --ignore-src -r -y || true
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-O3"

    - name: Create release package
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        
        # Create a release archive
        tar -czf master_ros2_ws_release.tar.gz install/
        
        echo "Release package created: master_ros2_ws_release.tar.gz"
        ls -la master_ros2_ws_release.tar.gz

    - name: Upload release asset
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: master_ros2_ws_release.tar.gz