name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  release-build:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop-full

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup ROS2 environment
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
        echo "ROS2 environment setup completed"

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update && apt-get install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          ros-humble-moveit \
          ros-humble-cv-bridge \
          ros-humble-vision-opencv \
          ros-humble-gazebo-ros-pkgs \
          ros-humble-tf2-geometry-msgs
        echo "Dependencies installed successfully"

    - name: Initialize rosdep
      shell: bash
      run: |
        rosdep init || echo "rosdep already initialized"
        rosdep update
        echo "rosdep initialized and updated"

    - name: Build optimized release
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        echo "Installing workspace dependencies..."
        rosdep install --from-paths . --ignore-src -r -y || true
        
        echo "Building workspace with optimization flags..."
        colcon build \
          --cmake-args \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-O3 -DNDEBUG" \
          --packages-skip-by-dep px4_msgs \
          --continue-on-error
        
        echo "Build completed successfully"

    - name: Verify build
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        
        echo "Verifying built packages..."
        ros2 pkg list | grep -E "(panda_moveit_control|my_opencv_package|panda_description|px4_ctrl)" || echo "Some packages not found"
        
        echo "Available packages in workspace:"
        ls -la install/

    - name: Create release package
      shell: bash
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        
        # Create release directory
        mkdir -p release_package
        
        # Copy install directory
        cp -r install/ release_package/
        
        # Create version info
        echo "Release Version: ${{ github.event.inputs.version || github.ref_name }}" > release_package/VERSION
        echo "Build Date: $(date)" >> release_package/VERSION
        echo "ROS2 Distribution: humble" >> release_package/VERSION
        
        # Create README for release
        cat > release_package/README.md << EOF
        # Master ROS2 Workspace Release
        
        ## Version: ${{ github.event.inputs.version || github.ref_name }}
        ## Build Date: $(date)
        ## ROS2 Distribution: Humble
        
        ## Contents:
        - Panda MoveIt Control Package
        - OpenCV Image Processing Package  
        - Panda Description Package
        - PX4 Control Package (if available)
        
        ## Installation:
        1. Extract this archive to your ROS2 workspace
        2. Source your ROS2 environment: \`source /opt/ros/humble/setup.bash\`
        3. Source this workspace: \`source install/setup.bash\`
        
        ## Usage:
        See individual package documentation for usage instructions.
        EOF
        
        # Create the release archive
        tar -czf master_ros2_ws_release_${{ github.event.inputs.version || github.ref_name }}.tar.gz release_package/
        
        echo "Release package created successfully"
        ls -la master_ros2_ws_release_*.tar.gz

    - name: Generate release notes
      shell: bash
      run: |
        cat > RELEASE_NOTES.md << EOF
        # Release Notes - ${{ github.event.inputs.version || github.ref_name }}
        
        ## 🚀 What's Included
        - **Panda MoveIt Control**: Advanced robotic arm control using MoveIt2
        - **OpenCV Image Processing**: Computer vision processing with ROS2 integration
        - **Panda Description**: URDF models and launch files for Panda robot
        - **PX4 Control**: Drone control interface (if dependencies available)
        
        ## 🔧 Technical Details
        - **ROS2 Distribution**: Humble
        - **Build Type**: Release (Optimized)
        - **Compiler Flags**: -O3 -DNDEBUG
        - **Build Date**: $(date)
        
        ## 📦 Installation
        \`\`\`bash
        # Extract the release
        tar -xzf master_ros2_ws_release_${{ github.event.inputs.version || github.ref_name }}.tar.gz
        
        # Source ROS2
        source /opt/ros/humble/setup.bash
        
        # Source workspace
        source release_package/install/setup.bash
        \`\`\`
        
        ## 🧪 Verification
        \`\`\`bash
        # Check available packages
        ros2 pkg list | grep -E "(panda_moveit_control|my_opencv_package|panda_description)"
        \`\`\`
        
        ## 📋 Requirements
        - Ubuntu 22.04
        - ROS2 Humble
        - MoveIt2
        - OpenCV
        - Gazebo (for simulation)
        EOF
        
        echo "Release notes generated"

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: release-package-${{ github.event.inputs.version || github.ref_name }}
        path: |
          master_ros2_ws_release_*.tar.gz
          RELEASE_NOTES.md
        retention-days: 90

    - name: Upload to GitHub Release (if triggered by release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./master_ros2_ws_release_${{ github.ref_name }}.tar.gz
        asset_name: master_ros2_ws_release_${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip

    - name: Create summary
      shell: bash
      run: |
        echo "## 🎉 Release Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Version**: ${{ github.event.inputs.version || github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **ROS2 Distribution**: Humble" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
        echo "- **Release Package**: master_ros2_ws_release_${{ github.event.inputs.version || github.ref_name }}.tar.gz" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Included Packages:" >> $GITHUB_STEP_SUMMARY
        echo "- Panda MoveIt Control" >> $GITHUB_STEP_SUMMARY
        echo "- OpenCV Image Processing" >> $GITHUB_STEP_SUMMARY  
        echo "- Panda Description" >> $GITHUB_STEP_SUMMARY
        echo "- PX4 Control (if available)" >> $GITHUB_STEP_SUMMARY