name: ROS2 Workspace CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: osrf/ros:humble-desktop-full

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup ROS2 environment
      run: |
        source /opt/ros/humble/setup.bash
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          ros-humble-moveit \
          ros-humble-cv-bridge \
          ros-humble-vision-opencv \
          ros-humble-gazebo-ros-pkgs \
          ros-humble-tf2-geometry-msgs

    - name: Initialize rosdep
      run: |
        rosdep init || true
        rosdep update

    - name: Install workspace dependencies
      run: |
        source /opt/ros/humble/setup.bash
        rosdep install --from-paths . --ignore-src -r -y || true

    - name: Build specific packages
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --packages-select \
          panda_moveit_control \
          my_opencv_package \
          panda_description \
          --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Source workspace and test
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        # Add basic smoke tests
        ros2 pkg list | grep panda_moveit_control
        ros2 pkg list | grep my_opencv_package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          log/
          build/
